[mqtt]
broker_url = "tcp://test.mosquitto.org:1883"

[bot]
token = "<telegram token>"
channel_id = 1234567890

[[subscriptions]]
topic = "sensor/temperature"

[[subscriptions]]
topic = "binary_sensor/openclose_2"
