[general]
host = "0.0.0.0" # Address used by the HTTP server
port = 8080 # Port used by the HTTP server

[mqtt]
broker_url = "tcp://test.mosquitto.org:1883"

[bot]
type = "telegram" # The only one supported atm
token = "<telegram token>"
channel_id = 1234567890

[[commands]] # Receive a command from the bot and send a message to MQTT
command = "on" # Listens for the command /on in the bot
topic = "homeassistant/switch1" # MQTT topic to publish the message to
message = "ON" # The value of the MQTT message
feedback_message = "Switched on" # The message to send back to bot after sending to MQTT
help = "Switch on the light in the kitchen"

[[subscriptions]]
label = "Kitchen temperature"
topic = "sensor/temperature"
repeat = true # Send all messages to bot
repeat_only_if_different = true # Repeat only if different from previous value
    [subscriptions.alarm] # Activate an alarm on this subscription
    operator = "greater_than" # greater_than, less_than or equal_to
    value = 20.0 # The alarm is triggered if the value is > 20.0 and a message is sent

[[subscriptions]]
topic = "binary_sensor/openclose_2"
repeat = false

[[intents]]
action = "switch-on"
room = "kitchen"
topic = "rooms/kitchen/Power"
message = "ON"
