name: Build and test master and PR
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: |
        go test ./...

    - name: Build
      run: |
        cd cmd/her
        go build -v .
